obstacle_range: 3.0
raytrace_range: 3.5
footprint: [[0.23,0.2],[-0.23,0.2],[-0.23,-0.2],[0.23,-0.2]]
#footprint: [[0.18,0.15],[-0.18,0.15],[-0.18,-0.15],[0.18,-0.15]]
inflation_radius: 0.15
max_obstacle_height: 0.4
min_obstacle_height: 0.05
observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0.3}
