DWAPlannerROS:

   max_vel_x: 0.2
   min_vel_x: 0.1
   max_vel_y: 0.2  # zero for a differential drive robot
   min_vel_y: 0.1
   max_trans_vel: 0.2
   min_trans_vel: 0.05
   max_rot_vel: 0.5
   min_rot_vel: 0.3
   escape_vel: -0.15
   acc_lim_x: 0.02
   acc_lim_y: 0.02 # zero for a differential drive robot
   acc_lim_theta: 1.0
   
   yaw_goal_tolerance: 0.15 
   xy_goal_tolerance: 0.15  # 15 cm

   path_distance_bias : 30.0
   goal_distance_bias : 24.0
   forward_point_distance : 0.325
   occdist_scale : 0.04
   stop_time_buffer : 0.3
   scaling_speed : 0.25
   max_scaling_factor : 0.2

   sim_time: 3.0
   vx_samples: 20
   vy_samples: 0 # zero for a differential drive robot
   vtheta_samples: 40
   
   oscillation_reset_dist: 0.05
   
   publish_traj_pc : true
   publish_cost_grid_pc : true
   global_frame_id : /map
 
