global_costmap:
   global_frame: /map
   robot_base_frame: /base_footprint
   update_frequency: 4.0
   publish_frequency: 0
   static_map: false
   rolling_window: false
   resolution: 0.05
   transform_tolerance: 3.0
   map_type: costmap
