local_costmap:
   global_frame: /map
   robot_base_frame: /base_footprint
   update_frequency: 4.0
   publish_frequency: 4.0
   static_map: false
   rolling_window: true
   width: 3.0
   height: 3.0
   resolution: 0.05   #should same as map.yaml file
   transform_tolerance: 3.0
   map_type: costmap

