# For a direct USB cable connection, the port name is typically
# /dev/ttyACM# where is # is a number such as 0, 1, 2, etc
# For a wireless connection like XBee, the port is typically
# /dev/ttyUSB# where # is a number such as 0, 1, 2, etc.

port: /dev/ttyACM0
baud: 57600
timeout: 0.5

rate: 50
sensorstate_rate: 10

use_base_controller: True
base_controller_rate: 10

# For a robot that uses base_footprint, change base_frame to base_footprint
base_frame: base_footprint

# === Robot drivetrain parameters
wheel_diameter: 0.1
wheel_track: 0.26
encoder_resolution: 12.9688
gear_reduction: 64
motors_reversed: True
debugPID: False
linear_scale_correction: 0.969
angular_scale_correction: 1.05

# === PID parameters
AWheel_Kp: 50
AWheel_Kd: 15
AWheel_Ki: 0
AWheel_Ko: 50

BWheel_Kp: 50
BWheel_Kd: 15
BWheel_Ki: 0
BWheel_Ko: 50

CWheel_Kp: 50
CWheel_Kd: 16
CWheel_Ki: 0
CWheel_Ko: 50

DWheel_Kp: 50
DWheel_Kd: 16
DWheel_Ki: 0
DWheel_Ko: 50

accel_limit: 0.2

sensors: {
  #motor_current_left:   {pin: 0, type: PololuMotorCurrent, rate: 5},
  #motor_current_right:  {pin: 1, type: PololuMotorCurrent, rate: 5},
  #ir_front_center:      {pin: 2, type: GP2D12, rate: 10},
  #sonar_front_center:   {pin: 5, type: Ping, rate: 10},
  #arduino_led:          {pin: 13, type: Digital, rate: 5, direction: output}
}
